version: '3.7'

services:
  api_container:
    container_name: asistencias_un_api
    build: ./
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    env_file: .env
    depends_on: 
      - mongodb_container
    ports:
      - ${NODEJS_PORT}:${NODEJS_PORT}
    networks:
      - asistencias_un_network
  mongodb_container:
    image: mongo:latest
    container_name: asistencias_un_db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    volumes: 
      - ./config/init_database.sh:/docker-entrypoint-initdb.d/init_database.sh
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    networks:
      - asistencias_un_network

networks:
  asistencias_un_network:
    driver: bridge